# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('cost', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=500)),
                ('image', models.CharField(default='', max_length=50)),
                ('image_num', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date service')),
            ],
        ),
    ]
