# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180404_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
