# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180404_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
    ]
